import Layout from "@/layout/Layout";
import "./globals.css";
import { yekan } from "@/utils/font";
import NextAuthProvider from "@/providers/NextAuthProvider";

export const metadata = {
  title: "Real State App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={yekan.className}>
        <NextAuthProvider>
          <Layout>{children}</Layout>
        </NextAuthProvider>
      </body>
    </html>
  );
}
